version: '3'
services:
  postgresql:
    restart: always
    image: yassan/postgresql:10-pgadmin4
    ports:
      - "5432:5432"
    env_file:
      - .env_db_pg
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
      - ./data:/var/lib/postgresql
  pgadmin:
    restart: always
    image: dpage/pgadmin4:4
    env_file:
      - .env_pgadmin4
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - /etc/timezone:/etc/timezone:ro 
       - ./data-pgadmin:/root/.pgadmin
    ports:
      - "10083:80"
    links:
      - postgresql
    depends_on:
      - postgresql
