version: '3'
services:
  postgresql:
    restart: always
    image: yassan/postgresql:10-1
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
  
      - DB_USER=
      - DB_PASS=
      - DB_NAME=
      - DB_TEMPLATE=
      - DB_EXTENSION=pgroonga
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    volumes:
      - ./data:/var/lib/postgresql
  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4:4
    environment:
      TZ: "Asia/Tokyo"
      PGADMIN_DEFAULT_EMAIL: hoge@huga.com
      PGADMIN_DEFAULT_PASSWORD: passw0d
    volumes:
       - ./data-pgadmin:/root/.pgadmin
    ports:
      - "8100:80"
    links:
      - postgresql
    depends_on:
      - postgresql
